apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    isDefault: true
    jsonData:
      defaultDatabase: agentlens
      port: 9000
      protocol: native
      secure: false
      username: default
      tlsSkipVerify: true
    secureJsonData:
      password: ""
    editable: true
